### PR TITLE
merge #123 into dev

### LINKED ISSUE #123: fix: convert all pool tokens to token at maturity
This fix addresses the following scenario:

1. a pool matures.
2. `swap-x-for-y` and `swap-y-for-x` is no longer supported.
3. no more rebalancing of pool as a result.
4. `yield-token` holder does not immediately burn `yield-token` to release the relevant `token`.
5. between the expiry and the burn, the value of the now-static pool falls below `token` value.

### PR DESCRIPTION
**Pull request by fiftyeightandeight**
closes #123

### CODE REVIEW

**Comment by JBotwina** [comment]
@fiftyeightandeight  As per discussion with @hyossid, we do not need the alex-multisig-registry at the moment, but it might be useful in the future. I have created a WIP (Work-in-progress) folder outside of contracts/ that can hold all contracts that we want to save for future reference.

**Comment by JBotwina** [comment]
@fiftyeightandeight 

Description of current error coming from alex-crp-wbtc-usda-4380.clar:
https://www.loom.com/share/9d545c2317574e38b57654d57ca81e2d

**Comment by fiftyeightandeight** [comment]
> @fiftyeightandeight 
> 
> 
> 
> Description of current error coming from alex-crp-wbtc-usda-4380.clar:
> 
> https://www.loom.com/share/9d545c2317574e38b57654d57ca81e2d

What is alex-crp-wbtc-usda-4380.clar? Can't find such a contract?

**Comment by fiftyeightandeight** [comment]
@JBotwina think you were looking at the error output of `clarinet check` wrongly. The highlight indicates either of the two - it is a problem or an error somewhere else affects this line. 
Did you check what the first line of the output says? Normally that is the root cause.
In any case, I upgraded clarinet to 0.15.1 and found a bug (missing ending bracket).
Please see again?

**Comment by JBotwina** [comment]
@fiftyeightandeight
This branch is missing the function set-fee-to-address under the yield-token-pool. Throws error in test cases.

image

https://github.com/alexgo-io/alex-v1/blob/fix/123/clarity/contracts/pool/yield-token-pool.clar

**Comment by fiftyeightandeight** [comment]
@JBotwina conflict resolved

**Comment by hyossid** [comment]
I think this can be merged to dev?

**Comment by JBotwina** [comment]
@hyossid if you checkout to the PR, it is still failing tests. I need to fix a few and talk to chan

**Comment by hyossid** [comment]
I think we can omit the procedure of passing testcases while we merge to dev but only assure that clarinet check passes. Anyway I feel like we have to build test cases from scratch and verify all the code merged together in dev. So my idea is that for now, when we push to dev, better to skip test cases or comment it

**Comment by JBotwina** [comment]
Ok. I think that’s probably the right decision. But I also think clarinet Check is failing. Like me check in a bit, if it passes then I’ll merge

**Comment by JBotwina** [comment]
Yes, clarinet check is failing. I'm going to have to review it with @fiftyeightandeight today, but I will try to fix as many as I can now.

**Pull request merged**
