### PR TITLE
Fix/fwp/testcases #180, #181 - FWP part

### PR DESCRIPTION
**Pull request by hyossid**
Q. I understand that pool tokens must be burn/mint by relevant pool. This can be done by adding simple assertion, but how about general fungible tokens like usda, wbtc ? It's not the matter of mining/burning in our project tho...

Q. I added the collect-fee part on multisig. The preliminary conditions for calling this function should be added, and discussion is required I guess.

Q. For the fixedpoint / non fixed point problem in Multisig, the problems I faced during the general test cases are fixed, but I can find only few of them. 

After this PR approved, I'll do the same in YTP.

### CODE REVIEW

**Comment by fiftyeightandeight** [comment]
> Q. I understand that pool tokens must be burn/mint by relevant pool. This can be done by adding simple assertion, but how about general fungible tokens like usda, wbtc ? It's not the matter of mining/burning in our project tho...

We need to mint/burn ourselves during the testnet (as fake money), but will rely on the respective deployed contracts when going to mainnet. So for now, they are just that - fakes that we control.

> Q. I added the collect-fee part on multisig. The preliminary conditions for calling this function should be added, and discussion is required I guess.

This could require quite a bit of set-up (different `fixed-weight-pool`, etc). Do you want to give it a try? Anything particular you want to ask?

> Q. For the fixedpoint / non fixed point problem in Multisig, the problems I faced during the general test cases are fixed, but I can find only few of them.

I still see many lines of code that mix up fixed-point and non-fixed point. For example, treatment of `(get yes-votes proposal)` on line 172 (which assumes fixed-point) and line 220 (which assumes non-fixed point), Also, line 219, where `total-supply`, which is not fixed-point, being mixed up with `threshold`, which is a fixed point.

> After this PR approved, I'll do the same in YTP.

**Comment by hyossid** [comment]
- Multisig floating point is fixed. Everything aside from necessary code (to get 80% of total supply) is changed to non-fixedpoint values.

- I will give a try for collecting fee regarding multisig. Just want to check what I understood is correct :

1. Multisig can call the collect-fee function at the pool anytime. (or shall there be block height limit to execute from multisig?)
2. When collect-fee is called, pool changes the fee value to USDA by swapping from Fixed Weight Pool.
3. Swapped USDA is sent to reserve-pool and corresponding ALEX token is minted. 
4. Mint ALEX Token is sent to Multisig from pool. 
5. Multisig receives ALEX Token 
6. Return ALEX Token to voters(pool token holder) following the proportion of votes.

**Comment by fiftyeightandeight** [comment]
> * Multisig floating point is fixed. Everything aside from necessary code (to get 80% of total supply) is changed to non-fixedpoint values.
> * I will give a try for collecting fee regarding multisig. Just want to check what I understood is correct :
> 
> 1. Multisig can call the collect-fee function at the pool anytime. (or shall there be block height limit to execute from multisig?)

Correct

> 2. When collect-fee is called, pool changes the fee value to USDA by swapping from Fixed Weight Pool.

Correct

> 3. Swapped USDA is sent to reserve-pool and corresponding ALEX token is minted.

Correct

> 4. Mint ALEX Token is sent to Multisig from pool.

Correct

> 5. Multisig receives ALEX Token

Correct

> 6. Return ALEX Token to voters(pool token holder) following the proportion of votes.

Not just the voters, but to all pool token holders, proportionally.

**Comment by fiftyeightandeight** [comment]
Check fails. Can you please review?

**Comment by hyossid** [comment]
There was clarinet update, Ill check it this evening

**Comment by hyossid** [comment]
Fixed, please review

**Pull request merged**
