### PR TITLE
generate new yield key and pool contracts #226

### PR DESCRIPTION
**Pull request by JBotwina**
Usage: 
```
node create-contracts.js <token> <collateral> <expiry>
```

https://www.loom.com/share/b3d7594a5e52496b9b0a17edf0dbf477

### CODE REVIEW

**Comment by fiftyeightandeight** [comment]
A few points that need attention:
- there are five contracts that need to be generated:
Screenshot 2021-09-23 at 6 58 29 PM

- if I run `node create-contracts.js wbtc usda 16793`, instead of contracts of form `yield-wbtc...` for example, the generated contracts have `yield-usda...` which is wrong.

- other than `key-token`, the generated contracts still refer to `59760` contracts.

**Comment by JBotwina** [comment]
@fiftyeightandeight 
Regarding point 2. I apologize, I should have been more explicit about the format. The format is:
```node create-contracts.js <token> <collateral> <expiry>```

**Comment by JBotwina** [comment]
Regarding point 3, I don't see the issue. Please ```git pull``` and see if it is still a problem

**Comment by fiftyeightandeight** [comment]
Still some issues:

After running the below:
Screenshot 2021-09-23 at 11 54 06 PM

- Multisig has references of 59760
Screenshot 2021-09-23 at 11 51 29 PM

- still seeing 59760 in 
Screenshot 2021-09-23 at 11 52 50 PM



> @fiftyeightandeight
> Regarding point 2. I apologize, I should have been more explicit about the format. The format is:
> `node create-contracts.js <token> <collateral> <expiry>`

The format is correct, except that what should be generated is not. For example, instead of `yield-<token>`, we currently have `yield-<collateral>`.

**Comment by JBotwina** [comment]
@fiftyeightandeight  put the token as the first parameter

**Pull request merged**
