### PR TITLE
Node deploy scripts

### PR DESCRIPTION
**Pull request by JBotwina**
@fiftyeightandeight @hecool108 @hyossid 
How to deploy:
https://www.loom.com/share/89e7701c7c8c436d92e4ff248469ebe6

Contract records:
https://www.loom.com/share/7dc3e26877a24e668cc1cc8af9f7b804

### CODE REVIEW

**Comment by fiftyeightandeight** [comment]
This looks good. Can we also automate copying of contract files from `/contracts/` to `/batches/`?

**Comment by JBotwina** [comment]
Yes, we definitely can.

**Comment by JBotwina** [comment]
@fiftyeightandeight However, at that point, it would probably be simpler and just as effective to just hard code the contract paths into an array and walk through the array. Therefore, I can get rid of the batches folder. If we need to add a contract, then we just add it to the contracts folder and add its path to the array in the right place.

**Comment by fiftyeightandeight** [comment]
> @fiftyeightandeight However, at that point, it would probably be simpler and just as effective to just hard code the contract paths into an array and walk through the array. Therefore, I can get rid of the batches folder. If we need to add a contract, then we just add it to the contracts folder and add its path to the array in the right place.

This is better.

**Comment by fiftyeightandeight** [comment]
> > @fiftyeightandeight However, at that point, it would probably be simpler and just as effective to just hard code the contract paths into an array and walk through the array. Therefore, I can get rid of the batches folder. If we need to add a contract, then we just add it to the contracts folder and add its path to the array in the right place.
> 
> This is better.

One this is done, then let me take a quick look and approve, before we merge to `dev`

**Comment by JBotwina** [comment]
@fiftyeightandeight updates have been made

**Pull request merged**
