### PR TITLE
test cases for reserve pool / shortfall added (#187)

### LINKED ISSUE #187: test(crp): test interaction with reserve-pool and dealing with short-fall

### PR DESCRIPTION
**Pull request by fiftyeightandeight**
closes #187

### CODE REVIEW

**Review by JBotwina — CHANGES_REQUESTED** [review]
Noticing now that the test/models files have Clarinet imports from v10 and v13. Is this expected?

**Comment by JBotwina** [comment]
Minor point: There are a lot of duplicated constants. Mostly, they are expected token balances. Should we just make these one variable and reuse the variable? It might be easier to check/update the tests in the future.

**Comment by fiftyeightandeight** [comment]
> Minor point: There are a lot of duplicated constants. Mostly, they are expected token balances. Should we just make these one variable and reuse the variable? It might be easier to check/update the tests in the future.

Which line of codes are you referring to, for example?

**Comment by fiftyeightandeight** [comment]
> Noticing now that the test/models files have Clarinet imports from v10 and v13. Is this expected?

Think we should be consistent. What happens if we all use v13?

**Comment by JBotwina** [comment]
> v13

@fiftyeightandeight I think in the past, we use v14. I think that is a safe bet

**Comment by fiftyeightandeight** [comment]
So the proposal is to use v14? I'm ok either way.

**Comment by JBotwina** [comment]
> So the proposal is to use v14? I'm ok either way.

Yup

**Comment by JBotwina** [comment]
1. 87, 88
2. 123,124
3. 159, 160
4. 182, 183
5. 264, 277, 281
6. 335, 336

There are quite a few more.

**Comment by fiftyeightandeight** [comment]
> 1. 87, 88
> 2. 123,124
> 3. 159, 160
> 4. 182, 183
> 5. 264, 277, 281
> 6. 335, 336
> 
> There are quite a few more.

Ah, they are outputs that change depending on what we input, so we should keep them as they are (but keep inputs as constant variable). Otherwise, we do endless scroll up and down.

**Comment by fiftyeightandeight** [comment]
changes requested reflected in the latest commit (upgrade clarinet to 0.14.0)

**Review by JBotwina — APPROVED** [review]

**Pull request merged**
