### PR TITLE
Swaps scripts

### PR DESCRIPTION
**Pull request by fiftyeightandeight**

### CODE REVIEW

**Review by JBotwina — COMMENTED** [review]
Occasionally I am getting a conflicting nonce for many of the transactions.

**Comment by JBotwina** [comment]
Seems like this is a common issue when you chain transactions using stacks.js. We must wait for the previous transaction to finish before we execute the following:
https://github.com/blockstack/stacks-wallet-web/issues/594#issuecomment-693202534

**Comment by fiftyeightandeight** [comment]
> Seems like this is a common issue when you chain transactions using stacks.js. We must wait for the previous transaction to finish before we execute the following:
> [blockstack/stacks-wallet-web#594 (comment)](https://github.com/blockstack/stacks-wallet-web/issues/594#issuecomment-693202534)
> 
> I can create a utility function to assist.

Yes, such a utility function would be indeed helpful!

**Comment by JBotwina** [comment]
I have fixed the conflicting nonce issue in the swap tests. 7698eff Please review. I can add the wait functionality to all of the transactions.

**Comment by JBotwina** [comment]
> > Seems like this is a common issue when you chain transactions using stacks.js. We must wait for the previous transaction to finish before we execute the following:
> > [blockstack/stacks-wallet-web#594 (comment)](https://github.com/blockstack/stacks-wallet-web/issues/594#issuecomment-693202534)
> > I can create a utility function to assist.
> 
> Yes, such a utility function would be indeed helpful!
> Do you think you can add such a function to the PR?

Yes, I can add it to all the transaction functions.

**Pull request merged**
